version: '2'
services:
  web:
    build: .
    ports:
    - "8080:8080"
    volumes:
    - .:/app
    links:
    - memcache
  memcache:
    ports:
      - "11211:11211"
    image: memcached
